require 'open-uri'
require 'nokogiri'
require 'pry'

require_relative './ny_state_fair_events/version'
require_relative './ny_state_fair_events/concert'
require_relative './ny_state_fair_events/scraper'
require_relative './ny_state_fair_events/parade'
require_relative './ny_state_fair_events/other'
require_relative './ny_state_fair_events/cli'
